// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD5ZOUIK7-2ACJizVznETjPLCyXRuj2Jw',
    appId: '1:711833617633:web:03afe55458fc91871ba3a0',
    messagingSenderId: '711833617633',
    projectId: 'innova-proyectos-jobs',
    authDomain: 'innova-proyectos-jobs.firebaseapp.com',
    storageBucket: 'innova-proyectos-jobs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD5ZOUIK7-2ACJizVznETjPLCyXRuj2Jw',
    appId: '1:711833617633:android:03afe55458fc91871ba3a0',
    messagingSenderId: '711833617633',
    projectId: 'innova-proyectos-jobs',
    storageBucket: 'innova-proyectos-jobs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA78lcE5N6wuKh1q6AvI8UMQXE-Ya48p0',
    appId: '1:711833617633:ios:ebb4ce9251a665ff1ba3a0',
    messagingSenderId: '711833617633',
    projectId: 'innova-proyectos-jobs',
    storageBucket: 'innova-proyectos-jobs.firebasestorage.app',
    iosBundleId: 'com.example.innovate',
  );
}


